base/urls.py
from django.urls import path
from . import views
from .views import *
from django.conf.urls.static import static
from django.conf import settings
 
app_name = 'base'

urlpatterns = [
    path('profile/edit_project/<int:pk>', views.edit_project, name='edit_project'),
    path('profile/delete_project/<int:pk>', views.delete_project, name='delete_project'),
    path('profile/edit_club/<int:pk>', views.edit_club, name='edit_club'),
    path('profile/delete_club/<int:pk>', views.delete_club, name='delete_club'),
    path('profile/edit_vacancy/<int:pk>', views.edit_vacancy, name='edit_vacancy'),
    path('profile/delete_vacancy/<int:pk>', views.delete_vacancy, name='delete_vacancy'),
    path('profile/add_project/', views.add_project, name='add_project'),
    path('profile/add_vacancy/', views.add_vacancy, name='add_vacancy'),
    path('profile/add_club/', views.add_club, name='add_club'),
    path('tasks/add_task', views.add_task, name='add_task'),
    path('profile/', views.profile, name='profile'),
    path('profile2/', views.profile2, name='profile2'),
    path('ege_dop/', views.ege_dop, name='ege_dop'),
    path('tasks/', views.tasks, name='tasks'),
    path('projects/', views.projects, name='projects'),
    path('vacancies/', views.vacancies, name='vacancies'),
    path('clubs/', views.clubs, name='clubs'),
    path('login/', views.Login, name='login'),
    path('logout/', views.Logout, name='logout'),
    path('registration/', views.registration, name='registration'),
    path('mental_health/', views.mental_health, name='mental_health'),
    path('', views.main, name='home'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

school/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
tz = timezone.get_default_timezone()

class Profile(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    grade = models.CharField(max_length=100)
    alias = models.URLField(max_length=200)
    user_id = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.alias

class Projects(models.Model):
    user_id = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    link = models.URLField(max_length=200)

    def __str__(self) -> str:
        return self.name
    
class Vacancies(models.Model):
    user_id = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    link = models.URLField(max_length=200)

    def __str__(self) -> str:
        return self.name

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT / media / user_<id>/<filename>
    return 'club/user_{0}/{1}'.format(instance.user_id, filename)

class Clubs(models.Model):
    user_id = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField()
    link = models.URLField(max_length=200)
    tags = models.CharField(max_length=200)
    img = models.ImageField(upload_to = user_directory_path)

    def __str__(self) -> str:
        return self.name
    
def task(instance, filename):
    return 'task/{0}/{1}'.format(instance.task_id.user_id, filename)
    
class Tasks(models.Model):
    user_id = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    category = models.CharField(max_length=50)
    text = models.TextField()
    answer = models.CharField(max_length=100)

class TasksFiles(models.Model):
    file = models.FileField(upload_to = task)
    task_id = models.ForeignKey(Tasks, default=None, on_delete=models.CASCADE, related_name='files')

class TaskComment(models.Model):
    task_id = models.ForeignKey(Tasks, default=None, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    created = models.DateTimeField(default=timezone.now)
    def __str__(self):
        return 'Заявка от {}'.format(self.created.astimezone(tz).strftime('%d.%m.%Y %H:%M'))

base/forms.py
from django import forms
from .models import *
from django.forms import ModelForm, TextInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'surname', 'grade', 'alias']


class RegisterUserForm(UserCreationForm):
    
    username = forms.CharField(label='Логин', 
                               widget=forms.TextInput(attrs={'id': 'username',
                                                            'class': "validate"
                                                             }))
    password1 = forms.CharField(label='Пароль', 
                               widget=forms.PasswordInput(attrs={'id': 'password1',
                                                            'class': "validate"
                                                                 }))
    password2 = forms.CharField(label='Повтор пароля', 
                               widget=forms.PasswordInput(attrs={'id': 'password2',
                                                            'class': "validate"
                                                                 }))
    
    class Meta:
        model = User
        fields = ['username', 'password2','password1']

base/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import *
from django.views.generic import *
from django.db import IntegrityError
import os
from django.conf import settings

from .forms import *
from .models import *

def registration(request):
    context = {
        'error_password': 0,
        'error_unique': 0,
        }
    try:
        if request.method == 'POST':
            name = request.POST['name']
            surname = request.POST['surname']
            grade = request.POST['grade']
            alias = request.POST['alias']
            password1 = request.POST['password1']
            password2 = request.POST['password2']
            if password1 != password2:
                context['error_password'] = 1
                return render(request, "registration.html", context)
            try:
                user = User.objects.create_user(username=alias, password=password1)
            except IntegrityError:
                context['error_unique'] = 1
                return render(request, "registration.html", context)
            login(request, user)
            Profile.objects.create(name=name, surname=surname, grade=grade, alias=alias, user_id=request.user)
            
            return redirect('base:profile')
    except:
        pass
    return render(request, "registration.html", context)

def Login(request):
    context = {
        'error_password': 0,
        }
    
    if request.method == 'POST':
        alias = request.POST.get('alias', False)
        password = request.POST.get('password', False)
        user = User.objects.get(username=alias)
        if user.check_password(password):
            login(request, user)
            return redirect('base:profile')
    return render(request, "login.html", context)

def Logout(request):
    logout(request)
    return redirect('base:profile')

def main(request):
    return render(request, "main2.html")

def mental_health(request):
    return render(request, "mental.html")








def tasks(request):
    context = {
        'tasks': Tasks.objects.all()[::-1],
    }
    if request.method == 'POST':
        comment = request.POST['comment']
        task_id = request.POST['task_id']
        TaskComment.objects.create(task_id=Tasks.objects.get(pk=task_id), text=comment)
    return render(request, "tasks5.html",context)

def ege_dop(request):
    return render(request, "ege-dop.html")








def projects(request):
    context = {
        'projects': Projects.objects.all()[::-1],
    }
    return render(request, "projects2.html", context)

def vacancies(request):
    context = {
        'vacancies': Vacancies.objects.all()[::-1],
    }
    return render(request, "vacancies.html", context)

def clubs(request):
    context = {
        'clubs': Clubs.objects.all()[::-1],
        'path': settings.MEDIA_ROOT,
    }
    return render(request, "clubs2.html", context)








def profile(request):
    try:
        context = {
            'vacancies': Vacancies.objects.filter(user_id=request.user)[::-1],
            'projects': Projects.objects.filter(user_id=request.user)[::-1],
            'clubs': Clubs.objects.filter(user_id=request.user)[::-1],
            'profile': Profile.objects.get(user_id=request.user),
        }
        if request.method == 'POST':
            name = request.POST['name']
            surname = request.POST['surname']
            grade = request.POST['grade']
            alias = request.POST['alias']
            user = Profile.objects.get(user_id=request.user)
            user.name = name
            user.surname = surname
            user.grade = grade
            user.alias = alias
            user.save()
            user = User.objects.get(pk=request.user.id)
            user.username = alias
            user.save()
            context['profile'] = Profile.objects.get(user_id=request.user)
        return render(request, "profile.html", context)
    except:
        return redirect('base:login')
    
def profile2(request):
    try:
        context = {
            'vacancies': Vacancies.objects.filter(user_id=request.user)[::-1],
            'projects': Projects.objects.filter(user_id=request.user)[::-1],
            'clubs': Clubs.objects.filter(user_id=request.user)[::-1],
            'profile': Profile.objects.get(user_id=request.user),
        }
        if request.method == 'POST':
            name = request.POST['name']
            surname = request.POST['surname']
            grade = request.POST['grade']
            alias = request.POST['alias']
            user = Profile.objects.get(user_id=request.user)
            user.name = name
            user.surname = surname
            user.grade = grade
            user.alias = alias
            user.save()
            user = User.objects.get(pk=request.user.id)
            user.username = alias
            user.save()
            context['profile'] = Profile.objects.get(user_id=request.user)
        return render(request, "profile2.html", context)
    except:
        return redirect('base:login')

def add_project(request):
    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        link = request.POST['link']
        Projects.objects.create(name=name,description=description,
                                link=link,user_id=request.user)

        return redirect('base:profile')
    return render(request, "form-work.html", context={'get_project': 0})


def edit_project(request, pk):
    get_project = Projects.objects.get(pk=pk)

    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        link = request.POST['link']
        get_project.name = name
        get_project.description = description
        get_project.link = link
        get_project.save()
        return redirect('base:profile')
        
    context = {
        'get_project': get_project,
    }
    return render(request, "form-work.html", context)

def delete_project(request, pk):
    Projects.objects.get(pk=pk).delete()
    return redirect('base:profile')

def add_vacancy(request):
    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        link = request.POST['link']
        Vacancies.objects.create(name=name,description=description,
                                link=link,user_id=request.user)

        return redirect('base:profile')
    return render(request, "form-work.html", context={'get_project_link': 1})


def edit_vacancy(request, pk):
    get_vacancy = Vacancies.objects.get(pk=pk)

    if request.method == 'POST':
        name = request.POST['name']
        description = request.POST['description']
        link = request.POST['link']
        get_vacancy.name = name
        get_vacancy.description = description
        get_vacancy.link = link
        get_vacancy.save()
        return redirect('base:profile')
        
    context = {
        'get_project': get_vacancy,
    }
    return render(request, "form-work.html", context)

def delete_vacancy(request, pk):
    Vacancies.objects.get(pk=pk).delete()
    return redirect('base:profile')

def add_club(request):
    context = {
        'get_club': 1,
        'get_project': 0,
    }
    if request.method == 'POST' or request.method == 'FILES':
        name = request.POST['name']
        description = request.POST['description']
        link = request.POST['link']
        tags = request.POST['tags']
        img = request.FILES['img']
        Clubs.objects.create(name=name,description=description,
                                link=link,user_id=request.user,img=img,tags=tags)

        return redirect('base:profile')
    return render(request, "form-work.html", context)


def edit_club(request, pk):
    get_club = Clubs.objects.get(pk=pk)
    context = {
        'get_project': get_club,
        'get_club': 1,
    }

    if request.method == 'POST' or request.method == 'FILES':
        name = request.POST['name']
        description = request.POST['description']
        link = request.POST['link']
        tags = request.POST['tags']
        try:
            img = request.FILES['img']
        
            if img != get_club.img:
                path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'media', get_club.img.name)
                if os.path.exists(path):
                    os.remove(path)
        except:
            pass
        get_club.name = name
        get_club.description = description
        get_club.link = link
        try:
            get_club.img = img
        except:
            pass
        get_club.tags = tags
        get_club.save()
        
        return redirect('base:profile')
        
    return render(request, "form-work.html", context)

def delete_club(request, pk):
    Clubs.objects.get(pk=pk).delete()
    return redirect('base:profile')

def add_task(request):
    if request.method == 'POST' or request.method == 'FILES':
        category = request.POST['category']
        text = request.POST['text']
        answer = request.POST['answer']
        task = Tasks.objects.create(user_id=request.user, category=category, text=text, answer=answer)
        for f in request.FILES.getlist('file'):
            TasksFiles.objects.create(task_id=task, file=f)
        return redirect('base:tasks')
    return render(request, "form-task.html")

base/templates/clubs2.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
  <meta charset="utf-8">
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!--metatextblock-->
  <title>clubs</title>
  <!-- Font Awesome -->
  <link
  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
  rel="stylesheet"
  />
  <!-- Google Fonts -->
  <link
  href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
  rel="stylesheet"
  />
  <!-- MDB -->
  <link
  href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.css"
  rel="stylesheet"
  />
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'src/clubs2.css'%}" />

<link rel="stylesheet" type="text/css" href="{% static 'src/profile2.css'%}" />
  
</head>

<style>
  nav li {
    padding: 0px 20px 0px 20px;
    text-transform: uppercase;
    font-size: 20px;
    color: #14a098;
  }

</style>

<body>
  
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #0f292f;height: 200px;">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <!-- Toggle button -->
      <button
        class="navbar-toggler"
        type="button"
        data-mdb-toggle="collapse"
        data-mdb-target="#navbarCenteredExample"
        aria-controls="navbarCenteredExample"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <i class="fas fa-bars"></i>
      </button>
  
      <!-- Collapsible wrapper -->
      <div
        class="collapse navbar-collapse justify-content-center"
        id="navbarCenteredExample"
      >
        <!-- Left links -->
        <ul class="navbar-nav mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'base:home' %}">Главная</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false">
              Ученику
            </a>
            <!-- Dropdown menu -->
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown" >
              <li>
                <a class="dropdown-item" href="{% url 'base:clubs' %}">Клубы</a>
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="{% url 'base:vacancies' %}">Вакансии</a>
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="#">Олимпиады</a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:projects' %}">Проекты</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:mental_health' %}">Ментальное здоровье</a>
          </li>
          <!-- Navbar dropdown -->
          <li class="nav-item dropdown">
            <a
              class="nav-link dropdown-toggle"
              href="#"
              id="navbarDropdown"
              role="button"
              data-mdb-toggle="dropdown"
              aria-expanded="false"
            >
              Поступление в вуз
            </a>
            <!-- Dropdown menu -->
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <a class="dropdown-item" href="{% url 'base:tasks' %}">База заданий</a>
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="{% url 'base:ege_dop' %}">Доп баллы ЕГЭ</a>
              </li>
              <li><hr class="dropdown-divider" /></li>
              <li>
                <a class="dropdown-item" href="#">Полезные материалы</a>
              </li>
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:profile' %}">Профиль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'base:logout' %}">Выход</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->
    </div>
    <!-- Container wrapper -->
  </nav>

  {% block content %}


  <div class="row mb-8">
    <div class="col-md-12 text-center">
      <a class="add" href="{% url 'base:add_club' %}"><button type="button" class="btn btn-lg add" autofocus>Добавить свой клуб</button></a>
    </div>
  </div>


  {% for club in clubs %}
  <div class="conteiner bg-light mx-auto club">
    <div class="row club-row">
      <div class="col-3"><img class="img-fluid" src="../../..{{club.img.url}}"/></div>
      <div class="col">
        <p class="name">{{ club.name }}</p>
        <p class="description">{{ club.description }}</p>
        <div class="row bot">
          <div class="col link mr-5 ">
            {{club.link}}
          </div>
          <div class="col tag">
            {{club.tags}}
          </div>
        </div>
        
      </div>
    </div>
  </div>
  {% endfor %}


  {%endblock%}

  <footer class="bg-black text-center text-white" style="height: 249px !important;">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
      <!--Grid row-->
      <section class="mb-4 mt-5">
        <a class="footer-link mr-4 text-white" href="#!" role="button"
          >О проекте</a>
  
        <a class="footer-link text-white" href="#!" role="button"
          >Контакты</a>
  
  
      <!--Grid row-->
    </div>
    <!-- Grid container -->
  
    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0) !important;">
      © 2023 Copyright: 
      Created by @LidaDavydova
    </div>
    <!-- Copyright -->
  </footer>


  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<!-- MDB -->
<script
  type="text/javascript"
  src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.4.1/mdb.min.js"
></script>
  </body>

  
</html>

base/templates/profile2.html
{% extends "clubs2.html" %}
{% load static %}

{% block content %}

<div class="row mt-5 mx-auto title">
     Профиль
</div>

<div class="conteiner">
     <div class="row mx-auto lk" style="width: 450px;">
          <div class="col">
               <p>Имя</p>
               <p>Фамилия</p>
               <p>Класс</p>
               <p>Alias</p>
          </div>
          <div class="col">
               <form method="POST" >
                    {% csrf_token %}
                    <input type="text" name="name" placeholder="Имя" value="{{ profile.name }}">
                    <input type="text" name="surname" placeholder="Фамилия" value="{{ profile.surname }}">
                    <input type="text" name="grade" placeholder="Класс" value="{{ profile.grade }}">
                    <input type="text" name="alias" placeholder="ссылка на Telegram" value="{{ profile.alias }}">

                    <button type="submit" class="tn-atom" style="height: 48px;">Сохранить</button>
               </form>
          </div>
     </div>
</div>

<div class="row" style="margin-top: 40px;">
     <div class="profile">
          <div class="conteiner club mx-auto">
               
               <div class="row" style="margin: 15px;text-align: center;">
                    <h4>Мои клубы</h4>
               </div>
               <div class="row">
                    <section class="">
                         <div class="tbl-header">
                         <table cellspacing="0" cellpadding="0" border="0">
                         <thead>
                              <tr>
                              <th><div class="item-text1">Имя</div></th>
                              <th><div class="item-text2">Описание</div></th>
                              <th><div class="item-text3">Ссылка</div></th>
                              <th><div class="">Редактировать</div></th>
                              <th><div class="">Удалить</div></th>
                              </tr>
                         </thead>
                         </table>
                         </div>
                         <div class="tbl-content">
                         <table cellspacing="0" cellpadding="0" border="0">
                         <tbody>
                              {% for club in clubs %}
                              <tr>
                                   <td><div class="item-text1">{{ club.name }}</div></td>
                                   <td><div class="item-text2">{{ club.description }}</div></td>
                                   <td><div class="item-text3">{{club.link}}</div></td>
                                   <th><div><a href="{% url 'base:edit_club' club.id %}">Редактировать</a></div></th>
                                   <th><div><a href="{% url 'base:delete_club' club.id %}">Удалить</a></div></th>
                              </tr>
                              {% endfor %}
                         </tbody>
                         </table>
                         </div>
                    </section>
               </div>
          </div>
          <div class="conteiner vacancies mx-auto">
               <div class="row" style="margin: 15px;text-align: center;">
                    <h4>Мои вакансии</h4>
               </div>
               <div class="row">
                    <section class="">
                         <div class="tbl-header">
                         <table cellspacing="0" cellpadding="0" border="0">
                         <thead>
                              <tr>
                              <th><div class="item-text1">Имя</div></th>
                              <th><div class="item-text2">Описание</div></th>
                              <th><div class="item-text3">Ссылка</div></th>
                              <th><div class="">Редактировать</div></th>
                              <th><div class="">Удалить</div></th>
                              </tr>
                         </thead>
                         </table>
                         </div>
                         <div class="tbl-content">
                         <table cellspacing="0" cellpadding="0" border="0">
                         <tbody>
                              {% for vacancy in vacancies %}
                                <tr>
                                  <td><div class="item-text1">{{ vacancy.name }}</div></td>
                                  <td><div class="item-text2">{{ vacancy.description }}</div></td>
                                  <td><div class="item-text3">{{ vacancy.link }}</div></td>
                                  <th><div><a href="{% url 'base:edit_vacancy' vacancy.id %}">Редактировать</a></div></th>
                                  <th><div><a href="{% url 'base:delete_vacancy' vacancy.id %}">Удалить</a></div></th>
                                </tr>
                              {% endfor %}
                         </tbody>
                         </table>
                         </div>
                    </section>
               </div>
          </div>
     </div>
</div>

{%endblock%}